# Updating Application


Configure haproxy socket

file: group_vars/prod.yml
```

  haproxy_socket: /var/run/haproxy.sock

```

Install netcat on lb

```
ansible lb -b -m yum -a "name=nc state=installed"
```

Create update script

file: update.yml
```
---
# Playbook for updating web server in batches
# filename: update.yml

- hosts: app
  become: yes
  vars:
    app:
      version: 1.6
  serial: 1

  pre_tasks:
    - name: take the app server out
      haproxy:
        host: '{{ inventory_hostname }}'
        state: disabled
      delegate_to: lb

  roles:
     - frontend

  post_tasks:
    - name: add server to loadbalancer
      haproxy:
        host: '{{ inventory_hostname }}'
        state: enabled
      delegate_to: lb

```

Deploy a new version with

```
ansible-playbook update.yml

```
